# Generated by Django 5.1.2 on 2024-11-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist_app', '0004_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_image_name', models.CharField(max_length=100, verbose_name='Nombre del Servicio')),
                ('service_image_description', models.TextField(verbose_name='Descripción')),
                ('service_image_image', models.ImageField(upload_to='services/', verbose_name='Imagen')),
            ],
        ),
    ]
