# Generated by Django 5.1.2 on 2024-11-16 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist_app', '0006_dentistimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceimage',
            name='service_image_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dentist_app.service'),
        ),
    ]
