# Generated by Django 5.1.2 on 2024-11-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist_app', '0007_alter_serviceimage_service_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceimage',
            name='service_image_name',
            field=models.CharField(max_length=100, verbose_name='Nombre del Servicio'),
        ),
    ]
